---
- name: Install and configure Nginx
  hosts: all
  become: true

  vars:
    source_file: /home/ubuntu/ansible/myweb.html
    destin_file: /var/www/html/index.html

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Allow port 80 through UFW
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Create directory
      become: true

      file:
        path: /home/ubuntu/opt/myapt
        state: directory
        mode: '0755'

    - name: Copy file to target folder
      copy:
        src: file1.1.txt
        dest: /home/ubuntu/opt/myapt/file1.1.txt

    - name: Copy myweb to server
      copy:
        src: "{{ source_file }}"
        dest: "{{ destin_file }}"
        mode: '0555'
